"use client";
import {alhamdUnitLabel} from "@/lib/alhamd-units";
import {useI18n} from '@/components/i18n/I18nProvider';
import {ThermalPrinter} from './ThermalPrinter';
import {formatMoney} from '@/lib/utils';
import type {PosReceipt} from '@/lib/thermal-print';
export function InvoiceView({receipt,restaurantId,fallbackName}:{receipt:PosReceipt;restaurantId:string;fallbackName:string}){
 const {locale}=useI18n();const l=(a:string,e:string)=>locale==='ar'?a:e;const f=receipt.fiscal;const currency=receipt.currency??'GBP';const money=(v:number)=>formatMoney(v,currency);const sign=receipt.creditNote?-1:1;
 const title=receipt.creditNote?l('إشعار دائن','Credit note'):f?.invoice_kind==='full'||f?.invoice_kind==='simplified'?l('فاتورة ضريبية','VAT invoice'):l('إيصال بيع','Sales receipt');
 return <div className="space-y-4"><ThermalPrinter compact restaurantId={restaurantId} restaurantName={f?.legal_name??fallbackName} currency={currency} receipt={receipt}/>
 <article id="pos-receipt" className="rounded-2xl border bg-white p-5"><h1 className="text-xl font-semibold">{f?.legal_name??fallbackName}</h1><p>{f?.address}</p>{f?.registered&&<p>VAT / TRN: {f.vat_number}</p>}<h2 className="mt-4 font-semibold">{title} {receipt.creditNote?`CN-${receipt.number}`:receipt.documentNumber??`#${receipt.number}`}</h2>{receipt.creditNote&&<p>{l('مرجع الفاتورة الأصلية','Original invoice reference')}: {receipt.originalDocumentNumber??`#${receipt.number}`}</p>}
 <p className="text-sm">{l('تاريخ الإصدار','Issue date')}: {new Date(receipt.creditNote?receipt.creditDate??receipt.createdAt:receipt.createdAt).toLocaleString(locale==='ar'?'ar-EG':'en-GB',{timeZone:f?.timezone??'UTC'})}</p><p className="text-sm">{l('تاريخ التوريد / الدفع','Supply / payment date')}: {new Date(receipt.paidAt??receipt.createdAt).toLocaleString(locale==='ar'?'ar-EG':'en-GB',{timeZone:f?.timezone??'UTC'})}</p>
 {f?.customer?.name&&<p className="mt-2">{l('العميل','Customer')}: {f.customer.name} · {f.customer.address} {f.customer.vat_number&&`VAT / TRN: ${f.customer.vat_number}`}</p>}
 <table className="my-3 w-full table-fixed border-collapse text-sm"><colgroup><col className="w-[10%]"/><col className="w-[14%]"/><col className="w-[38%]"/><col className="w-[18%]"/><col className="w-[20%]"/></colgroup><thead><tr>{[l('الكمية','Qty'),l('الوحدة','Unit'),l('اسم الصنف','Item'),l('السعر','Price'),l('الإجمالي','Total')].map(h=><th key={h} className="border p-1 text-center">{h}</th>)}</tr></thead><tbody>{receipt.lines.map((line,i)=><tr key={i}><td className="border p-1 text-center">{line.quantity}</td><td className="break-words border p-1 text-center">{alhamdUnitLabel(line.variant,restaurantId)}</td><td className="break-words border p-1">{line.name}{f?.registered&&f.mode!=='egypt'&&<small className="block">{line.code} {line.rate}% · VAT {money(sign*(line.vat??0))}</small>}</td><td className="border p-1 text-center"><bdi>{(f&&f.mode!=='egypt'?(line.net??0)/line.quantity:line.price).toFixed(2)}</bdi></td><td className="border p-1 text-center"><bdi>{(sign*(f?.mode==='egypt'?line.price*line.quantity:line.gross??line.price*line.quantity)).toFixed(2)}</bdi></td></tr>)}</tbody></table>
 <p className="rounded bg-ink-900 px-2 py-1 text-center font-semibold text-white">{l('إجمالي الكميات','Total quantity')}: {receipt.lines.reduce((sum,line)=>sum+line.quantity,0)}</p>
 <p>{l('قبل الضريبة','Subtotal')}: {f ? money(sign*f.net) : money(sign*receipt.total)}</p>{f?.registered && <p>{l('الضريبة','VAT')}: {money(sign*f.vat)}</p>}<p className="mt-1 rounded bg-ink-900 px-2 py-1 text-center text-lg font-semibold text-white">{l('الإجمالي','Total')}: {money(sign*receipt.total)}</p>
 <p>{l('المدفوع','Paid')}: {money(receipt.fiscalState==='unpaid'?0:sign*receipt.total)}</p><p>{l('المتبقي','Due')}: {money(receipt.fiscalState==='unpaid'?sign*receipt.total:0)}</p>
 {f?.mode !== 'egypt' && f?.breakdown.map(b=><p key={`${b.code}-${b.rate}`} className="mt-2 text-xs">{b.code} {b.rate}% · {l('قبل الضريبة','Net')} {money(sign*b.net)} · VAT {money(sign*b.vat)} · {money(sign*b.gross)}</p>)}
 <p className="mt-4 text-sm">{receipt.fiscalState==='unpaid'?l('غير مدفوع','Unpaid'):receipt.payment==='transfer'?l('تحويل خارجي — تأكيد يدوي','External transfer — manually confirmed'):receipt.payment} {receipt.creditNote&&l('استرداد','Refund')}</p>{receipt.note&&<p>{receipt.note}</p>}
 {f?.invoice_kind==='receipt'&&f.registered&&<p className="mt-3 text-xs">{f.mode==='saudi'?l('إيصال بيع. الربط بالفوترة الإلكترونية ZATCA غير مفعّل.','Sales receipt. ZATCA electronic invoicing is not connected.'):l('إيصال بيع، وليس فاتورة ضريبية كاملة.','Sales receipt, not a full VAT invoice.')}</p>}
 {!f&&<p className="mt-3 text-xs">{l('طلب تاريخي. بيانات VAT وقت البيع غير مسجلة.','Historical order. VAT at the time of sale was not recorded.')}</p>}</article></div>;
}
