"use client";
import { useRef,useState,useTransition } from 'react';
import Link from 'next/link';
import { useI18n } from '@/components/i18n/I18nProvider';
import { SmartImage } from '@/components/ui/SmartImage';
import { Button } from '@/components/ui/Button';
import { checkoutPos } from '@/lib/actions/pos';
import { formatMoney,cn } from '@/lib/utils';
import type { ProductWithVariants,Category,RestaurantTable } from '@/lib/types';
type Line={variantId:string;name:string;variant:string;price:number;quantity:number};
export function PosScreen({restaurantName,currency,products,categories,tables}:{restaurantName:string;currency:string;products:ProductWithVariants[];categories:Category[];tables:RestaurantTable[]}){
 const {locale}=useI18n();const ar=locale==='ar';const label=(a:string,e:string)=>ar?a:e;
 const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [cart,setCart]=useState<Line[]>([]);
 const [table,setTable]=useState('');const [payment,setPayment]=useState<'cash'|'card'>('cash');const [received,setReceived]=useState('');const [note,setNote]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition();
 const [receipt,setReceipt]=useState<{number:number;total:number;received:number;lines:Line[]}|null>(null);
 const request=useRef<string|null>(null);
 const money=(v:number)=>formatMoney(v,currency);const total=Math.round(cart.reduce((sum,l)=>sum+l.price*l.quantity,0)*100)/100;
 const shown=products.filter(p=>(category==='all'||p.category_id===category)&&p.name.toLowerCase().includes(query.toLowerCase()));
 function add(p:ProductWithVariants,v:ProductWithVariants['product_variants'][number]){request.current=null;setReceipt(null);setCart(old=>{const found=old.find(l=>l.variantId===v.id);return found?old.map(l=>l.variantId===v.id?{...l,quantity:Math.min(99,l.quantity+1)}:l):[...old,{variantId:v.id,name:p.name,variant:v.name,price:v.price,quantity:1}];});}
 function quantity(id:string,delta:number){request.current=null;setCart(old=>old.map(l=>l.variantId===id?{...l,quantity:Math.min(99,l.quantity+delta)}:l).filter(l=>l.quantity>0));}
 function pay(){setError('');if(!cart.length)return;request.current??=crypto.randomUUID();start(async()=>{try{const result=await checkoutPos({requestId:request.current!,lines:cart.map(({variantId,quantity})=>({variantId,quantity})),tableId:table||null,payment,received:payment==='cash'?Number(received):total,note});if(!result.ok){setError(result.message);return;}setReceipt({number:result.orderNumber,total:result.total,received:result.received,lines:cart});setCart([]);setReceived('');setNote('');request.current=null;}catch{setError(label('الاتصال اتقطع. حاول تاني بنفس الطلب.','Connection interrupted. Retry this order.'));}});}
 return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{label('الكاشير','Point of sale')}</h1><p className="text-sm text-ink-500">{restaurantName}</p></div><Link href="/dashboard/orders" className="rounded-xl border border-ink-200 bg-white px-4 py-2 text-sm">{label('متابعة الطلبات','View orders')}</Link></header>
 <div className="grid items-start gap-5 xl:grid-cols-[1fr_380px]"><section><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={label('ابحث عن منتج','Search products')} aria-label={label('ابحث عن منتج','Search products')} className="h-12 w-full rounded-2xl border border-ink-200 bg-white px-4"/><div className="my-4 flex gap-2 overflow-x-auto pb-2">{[{id:'all',name:label('الكل','All')},...categories].map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={cn('shrink-0 rounded-full px-4 py-2 text-sm',category===c.id?'bg-ink-900 text-white':'bg-white text-ink-600')}>{c.name}</button>)}</div>
 {shown.length===0&&<div className="rounded-2xl border border-dashed border-ink-300 p-8 text-center"><p>{label('مفيش منتجات متاحة','No products available')}</p><Link href="/dashboard/catalog" className="mt-3 inline-block text-brand-700">{label('ضيف من المنيو العام','Add from catalog')}</Link></div>}
 <div className="grid grid-cols-2 gap-3 md:grid-cols-3 2xl:grid-cols-4">{shown.map(p=><article key={p.id} className="overflow-hidden rounded-2xl border border-ink-200 bg-white"><div className="relative aspect-[4/3] bg-ink-100"><SmartImage src={p.image_url} alt={p.name} sizes="200px"/></div><div className="p-3"><h2 className="mb-2 font-semibold">{p.name}</h2><div className="flex flex-col gap-2">{p.product_variants.filter(v=>v.is_active).map(v=><button key={v.id} disabled={pending} onClick={()=>add(p,v)} className="flex min-h-11 items-center justify-between gap-2 rounded-xl bg-brand-50 px-3 py-2 text-start text-sm text-brand-800 hover:bg-brand-100"><span>{p.product_variants.length>1?v.name:label('إضافة','Add')}</span><strong>{money(v.price)}</strong></button>)}</div></div></article>)}</div></section>
 <aside className="rounded-3xl border border-ink-200 bg-white p-5 xl:sticky xl:top-24"><h2 className="mb-4 text-lg font-semibold">{label('الطلب الحالي','Current order')}</h2>
 <fieldset disabled={pending} className="space-y-4"><select value={table} onChange={e=>{setTable(e.target.value);request.current=null;}} aria-label={label('نوع الطلب','Order type')} className="h-11 w-full rounded-xl border border-ink-200 px-3"><option value="">{label('تيك أواي','Takeaway')}</option>{tables.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select>
 {!cart.length?<p className="py-8 text-center text-sm text-ink-400">{label('اختار المنتجات عشان تبدأ طلب جديد','Choose products to start an order')}</p>:<ul className="max-h-96 divide-y divide-ink-100 overflow-y-auto">{cart.map(l=><li key={l.variantId} className="py-3"><div className="flex justify-between gap-2"><span className="text-sm font-medium">{l.name}<small className="block text-ink-400">{l.variant}</small></span><strong className="text-sm">{money(l.price*l.quantity)}</strong></div><div className="mt-2 flex items-center gap-3"><button aria-label={label('تقليل الكمية','Decrease quantity')} onClick={()=>quantity(l.variantId,-1)} className="size-9 rounded-lg bg-ink-100">−</button><span>{l.quantity}</span><button aria-label={label('زيادة الكمية','Increase quantity')} onClick={()=>quantity(l.variantId,1)} className="size-9 rounded-lg bg-ink-100">+</button></div></li>)}</ul>}
 <input value={note} onChange={e=>setNote(e.target.value)} maxLength={400} placeholder={label('ملاحظة للطلب','Order note')} aria-label={label('ملاحظة للطلب','Order note')} className="h-11 w-full rounded-xl border border-ink-200 px-3 text-sm"/>
 <div className="flex justify-between border-t border-ink-100 pt-4 text-xl font-semibold"><span>{label('الإجمالي','Total')}</span><span>{money(total)}</span></div>
 <div className="grid grid-cols-2 gap-2">{(['cash','card'] as const).map(p=><button key={p} onClick={()=>setPayment(p)} className={cn('rounded-xl border py-3 text-sm',payment===p?'border-brand-500 bg-brand-50 text-brand-700':'border-ink-200')}>{p==='cash'?label('كاش','Cash'):label('بطاقة','Card')}</button>)}</div>
 {payment==='cash'&&<label className="block text-sm">{label('المبلغ المستلم','Amount received')}<input type="number" min={total} step="0.01" value={received} onChange={e=>setReceived(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-ink-200 px-3"/><span className="mt-2 block text-ink-500">{label('الباقي','Change')}: {money(Math.max(0,Number(received)-total))}</span></label>}
 {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
 <Button className="w-full" size="lg" loading={pending} disabled={!cart.length||(payment==='cash'&&Number(received)<total)} onClick={pay}>{label('تأكيد الدفع','Confirm payment')}</Button></fieldset>
 {receipt&&<div className="mt-4 rounded-2xl bg-emerald-50 p-4"><p role="status" className="font-semibold text-emerald-800">{label('تم حفظ الطلب','Order saved')} #{receipt.number}</p><Button variant="secondary" className="mt-3 w-full" onClick={()=>window.print()}>{label('طباعة الفاتورة','Print receipt')}</Button></div>}
 </aside></div>
 {receipt&&<div id="pos-receipt" className="hidden"><h1>{restaurantName}</h1><p>#{receipt.number}</p>{receipt.lines.map(l=><div key={l.variantId}><span>{l.name} {l.variant} × {l.quantity}</span><strong>{money(l.price*l.quantity)}</strong></div>)}<hr/><p>{label('الإجمالي','Total')}: {money(receipt.total)}</p><p>{label('المستلم','Received')}: {money(receipt.received)}</p><p>{label('الباقي','Change')}: {money(receipt.received-receipt.total)}</p></div>}
 </div>;
}
