"use client";
import {useActionState,useState} from 'react';
import {useI18n} from '@/components/i18n/I18nProvider';
import {saveTaxSettings} from '@/lib/actions/fiscal';
import {TAX_MODES,MARKET,taxAmounts,type TaxMode} from '@/lib/tax';
import type {Restaurant} from '@/lib/types';
import {SubmitButton} from '@/components/ui/SubmitButton';
export function TaxSettingsForm({restaurant:r}:{restaurant:Restaurant}) {
 const {locale}=useI18n();const label=(ar:string,en:string)=>locale==='ar'?ar:en;
 const [state,action]=useActionState(saveTaxSettings,null);const [mode,setMode]=useState<TaxMode>(r.tax_mode);
 const [rates,setRates]=useState(() => Object.fromEntries(TAX_MODES.filter(m=>m!=='none').map(m=>[m,{standard:r.tax_rates?.[m]?.standard??MARKET[m].standard,reduced:r.tax_rates?.[m]?.reduced??(m==='uk'?5:0)}])));
 const [pricing,setPricing]=useState(r.prices_include_vat?'inclusive':r.menu_prices_include_vat===false?'exclusive_net':'exclusive_gross');
 const example=taxAmounts(100,1,rates[mode]?.standard??0,pricing==='inclusive');
 const field='mt-2 h-11 w-full rounded-xl border border-ink-200 bg-white px-3 text-sm';
 return <form action={action} className="space-y-4 rounded-2xl border border-ink-200 bg-white p-5">
 <h2 className="font-semibold">{label('الضريبة وبيانات الفاتورة','Tax and invoice settings')}</h2>
 <label className="block text-sm">{label("بلد النشاط الضريبي","Tax country")}<select name="tax_mode" value={mode} onChange={e=>setMode(e.target.value as TaxMode)} className={field}>{TAX_MODES.map(m=><option value={m} key={m}>{m==='none'?label('بدون وضع ضريبي','No tax mode'):m==='uk'?'UK Tax Mode':m==='uae'?'UAE Tax Mode':m==='saudi'?'Saudi Tax Mode':label('مصر','Egypt')}</option>)}</select></label>
 {mode!=='none'&&<p className="text-xs text-ink-500">{MARKET[mode].currency} · {MARKET[mode].timezone} · {label('النسبة الافتراضية','Default rate')} {MARKET[mode].standard}%</p>}
 <label className="block text-sm">{label("مسجل ضريبيًا","VAT registered")}<select name="vat_registered" defaultValue={r.vat_registered?'true':'false'} className={field}><option value="false">{label('لا','No')}</option><option value="true">{label('نعم','Yes')}</option></select></label>
 <label className="block text-sm">{label("الرقم الضريبي","VAT Number / TRN")}<input name="vat_number" defaultValue={r.vat_number??''} maxLength={32} className={field}/></label>
 <label className="block text-sm">{label('اسم المنشأة القانوني','Legal business name')}<input name="legal_name" defaultValue={r.legal_name??r.name} maxLength={160} className={field}/></label>
 <label className="block text-sm">{label('عنوان المنشأة للفاتورة','Business invoice address')}<input name="tax_address" defaultValue={r.tax_address??r.address??''} maxLength={400} className={field}/></label>
 <fieldset className="space-y-3"><legend className="text-sm font-semibold">{label('نسب الضريبة لكل بلد (%)','Tax rates by country (%)')}</legend><div className="grid gap-3 sm:grid-cols-2">{TAX_MODES.filter(m=>m!=='none').map(m=><div key={m} className="rounded-xl border border-ink-200 p-3"><p className="text-sm font-medium">{m==='egypt'?label('مصر','Egypt'):m.toUpperCase()}</p><div className="mt-2 grid grid-cols-2 gap-2">{(['standard','reduced'] as const).map(code=><label key={code} className="text-xs">{code==='standard'?label('الأساسية','Standard'):label('المخفضة','Reduced')}<input name={`${m}_${code}`} type="number" min="0" max="100" step="0.01" required value={rates[m][code]} onChange={e=>setRates(previous=>({...previous,[m]:{...previous[m],[code]:Number(e.target.value)}}))} className={field}/></label>)}</div></div>)}</div><p className="text-xs text-ink-500">{label('اختار النسب والتصنيفات المناسبة لتسجيل منشأتك والمنتجات. التصنيف الصفري والمعفى يفضلوا 0%.','Set rates and categories appropriate to your registration and products. Zero and exempt remain 0%.')}</p></fieldset>
 <label className="block text-sm">{label('الأسعار الحالية في المينيو','Current menu prices')}<select name="pricing_mode" value={pricing} onChange={e=>setPricing(e.target.value)} className={field}><option value="inclusive">{label('شاملة الضريبة — الإجمالي يفضل نفس السعر','VAT inclusive — keep the same total')}</option><option value="exclusive_gross">{label('بدون الضريبة — اعرض السعر النهائي بالضريبة','VAT exclusive — show final prices including VAT')}</option><option value="exclusive_net">{label('بدون الضريبة — اعرض الأساسي وأضف VAT للإجمالي','VAT exclusive — show base prices, add VAT to total')}</option></select></label>
 <div className="rounded-xl bg-brand-50 p-3 text-sm"><p className="font-semibold">{label('مثال لسعر مدخل 100 (مع تفعيل التسجيل الضريبي)','Example: entered price 100 (when VAT registered)')}</p><p className="mt-1">{label('سعر المينيو','Menu price')}: {pricing==='exclusive_net'?100:example.gross.toFixed(2)} · {label('قبل الضريبة','Subtotal')}: {example.net.toFixed(2)} · VAT: {example.vat.toFixed(2)} · {label('الإجمالي','Total')}: {example.gross.toFixed(2)}</p></div>
 <p className="text-xs text-ink-500">{label('القيم المدخلة للمنتجات تفضل محفوظة؛ عرض السعر النهائي وحساب الضريبة يتغيروا حسب اختيارك بدون زيادة الضريبة مرتين. التغيير يطبق على الطلبات الجديدة فقط. البلد بيضبط العملة والتوقيت لكنه لا يحول قيمة الأسعار بين العملات. عند عدم التسجيل لا يتم تحصيل VAT.','Entered product values are preserved; displayed prices and tax calculation follow your choice without adding VAT twice. Changes affect new orders only. Country sets currency and timezone but does not convert prices. VAT is not charged when not registered.')}</p>
 {(mode==='saudi'||mode==='uae')&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{mode==='saudi'?label('حساب VAT والسجلات متاحين. الربط بالفوترة الإلكترونية لدى ZATCA غير مفعّل؛ الإيصال الحالي ليس فاتورة إلكترونية معتمدة.','VAT calculation and records are available. ZATCA electronic invoicing is not connected; this receipt is not a compliant electronic invoice.'):label('حساب VAT وبيانات TRN متاحين. الربط بمنظومة الفوترة الإلكترونية الإماراتية غير مفعّل.','VAT calculation and TRN details are available. UAE electronic invoicing is not connected.')}</p>}
 {state?.message&&<p role="status" className={state.ok?'text-sm text-emerald-700':'text-sm text-red-700'}>{state.message}</p>}
 <SubmitButton>{label('حفظ إعدادات الضريبة','Save tax settings')}</SubmitButton></form>;
}
