"use client";
import Link from 'next/link';
import {useState} from 'react';
import {useMenu} from '../MenuContext';
import {MenuImage} from '../MenuMedia';
import {useI18n} from '@/components/i18n/I18nProvider';
import {priceRange} from '@/lib/utils';
import {Icon} from '@/components/ui/Icons';
import type {ProductWithVariants} from '@/lib/types';

export function SupermarketMenu({offersOnly=false}:{offersOnly?:boolean}){
 const {data,currency,showPrices,openProduct,itemCount,setCartOpen}=useMenu();
 const {locale}=useI18n();const ar=locale==='ar';
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[slide,setSlide]=useState(0);
 const offers=data.offers??[];const offer=offers[slide%Math.max(1,offers.length)];
 const menuPath=data.menu_path??`/${data.restaurant.slug}/menu`,offersPath=menuPath.replace(/\/menu$/,'/offers');
 const needle=query.trim().toLocaleLowerCase();
 const groups=data.categories.filter(c=>!selected||c.id===selected).map(c=>({...c,products:c.products.filter(p=>!needle||`${p.name} ${p.description??''} ${c.name}`.toLocaleLowerCase().includes(needle))}));
 const allProducts=data.categories.flatMap(c=>c.products);
 function productCard(p:ProductWithVariants){
  return <button type="button" key={p.id} onClick={()=>openProduct(p)} className="flex flex-col rounded-2xl border border-neutral-100 p-3 text-start shadow-sm transition hover:border-red-300"><MenuImage src={p.image_url} alt={p.name} fit="contain" className="aspect-square w-full" sizes="(max-width:640px) 45vw, 240px"/><h3 className="mt-3 text-sm font-bold">{p.name}</h3>{p.description&&<p className="mt-1 line-clamp-2 text-xs text-neutral-500">{p.description}</p>}{showPrices&&<p className="mt-auto pt-3 text-sm font-bold text-red-600">{priceRange(p.product_variants.map(v=>Number(v.price)),currency)}</p>}<span className="mt-3 block rounded-lg border border-red-500 py-2 text-center text-xs font-semibold text-red-600">{ar?'اختيار +':'Choose +'}</span></button>;
 }
 const banner=<>{(offer?.image_url||data.restaurant.cover_url)&&<MenuImage src={offer?.image_url||data.restaurant.cover_url} alt="" fit="cover" className="absolute inset-0 h-full w-full opacity-30" sizes="100vw"/>}<div className="relative"><h2 className="text-3xl font-black leading-relaxed">{offer?offer.title:<>{ar?'كل احتياجاتك':'Everything you need'}<br/><span className="text-yellow-200">{ar?'من مكان واحد':'In one place'}</span></>}</h2><p className="mt-3 max-w-md whitespace-pre-line text-sm leading-7">{offer?offer.description:data.restaurant.description}</p>{offer&&<span className="mt-4 inline-block rounded-full bg-white px-5 py-2 text-sm font-bold text-red-600">{ar?'شاهد العرض ←':'View offer →'}</span>}</div></>;
 return <div className="min-h-screen bg-white pb-28 text-neutral-900"><main className="mx-auto max-w-5xl px-4">
 <header className="flex items-center justify-between gap-4 py-5"><div className="flex items-center gap-3">{data.restaurant.logo_url?<MenuImage src={data.restaurant.logo_url} alt={data.restaurant.name} className="size-12" sizes="48px"/>:<Icon.store className="size-9 text-red-600"/>}<div><h1 className="text-2xl font-black">{data.restaurant.name}</h1><p className="text-[10px] tracking-widest text-neutral-500">GROCERIES & MORE</p></div></div><button type="button" onClick={()=>setCartOpen(true)} aria-label={ar?'سلة المشتريات':'Shopping cart'} className="relative rounded-full border p-3"><Icon.receipt className="size-5"/>{itemCount>0&&<span className="absolute -top-2 -end-1 rounded-full bg-red-600 px-2 py-1 text-xs text-white">{itemCount}</span>}</button></header>
 {offersOnly?<>
  <Link href={menuPath} className="mb-5 inline-block text-sm font-semibold text-red-600">{ar?'← الرجوع للمنتجات':'← Back to products'}</Link><h2 className="mb-6 text-2xl font-black">{ar?'العروض الحالية':'Current offers'}</h2>
  {offers.map(o=><section id={`offer-${o.id}`} key={o.id} className="mb-8 scroll-mt-6 rounded-3xl border border-red-100 p-5">{o.image_url&&<MenuImage src={o.image_url} alt={o.title} fit="cover" className="mb-5 aspect-[2/1] w-full rounded-2xl" sizes="(max-width:640px) 95vw, 900px"/>}<h3 className="text-xl font-bold text-red-600">{o.title}</h3><p className="my-4 whitespace-pre-line text-sm leading-7 text-neutral-600">{o.description}</p>{o.ends_at&&<p className="mb-4 text-xs text-neutral-500">{ar?'آخر يوم للعرض: ':'Last offer day: '}{new Date(new Date(o.ends_at).getTime()-1).toLocaleDateString(ar?'ar-EG':'en-GB',{timeZone:data.restaurant.business_timezone??'Africa/Cairo'})}</p>}<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{allProducts.filter(p=>o.product_ids.includes(p.id)).map(productCard)}</div></section>)}
  {!offers.length&&<p className="rounded-2xl bg-neutral-50 p-8 text-center text-neutral-500">{ar?'لا توجد عروض متاحة حاليًا.':'No offers available right now.'}</p>}
 </>:<>
 <label className="relative block"><span className="sr-only">{ar?'ابحث عن منتج':'Search products'}</span><Icon.search className="absolute start-4 top-4 size-5 text-neutral-400"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?'ابحث عن منتج…':'Search a product…'} className="h-14 w-full rounded-2xl bg-neutral-100 ps-12 pe-4 outline-none focus:ring-2 focus:ring-red-500"/></label>
 <section aria-label={offer?(ar?'عروض المتجر':'Store offers'):(ar?'عن المتجر':'About the store')} className="mt-4 overflow-hidden rounded-3xl bg-red-600 text-white">{offer?<Link href={`${offersPath}#offer-${offer.id}`} className="relative block p-7 sm:p-10">{banner}</Link>:<div className="relative p-7 sm:p-10">{banner}</div>}{offers.length>1&&<div className="flex items-center justify-center gap-3 border-t border-white/20 px-4 py-3"><button type="button" aria-label={ar?'العرض السابق':'Previous offer'} onClick={()=>setSlide((slide+offers.length-1)%offers.length)} className="rounded-full bg-white/15 px-3 py-1">‹</button>{offers.map((o,i)=><button type="button" key={o.id} aria-label={o.title} aria-pressed={slide%offers.length===i} onClick={()=>setSlide(i)} className={`size-3 rounded-full ${slide%offers.length===i?'bg-white':'bg-white/40'}`}/>)}<button type="button" aria-label={ar?'العرض التالي':'Next offer'} onClick={()=>setSlide((slide+1)%offers.length)} className="rounded-full bg-white/15 px-3 py-1">›</button></div>}</section>
 <nav aria-label={ar?'أقسام السوبر ماركت':'Supermarket categories'} className="my-6 grid grid-cols-4 gap-x-2 gap-y-5 sm:grid-cols-6"><button type="button" aria-pressed={selected===null} onClick={()=>setSelected(null)} className="text-center text-xs font-semibold"><span className={`mx-auto mb-2 grid size-16 place-items-center rounded-full ${selected===null?'bg-red-100 ring-2 ring-red-500':'bg-neutral-100'}`}><Icon.grid className="size-6 text-red-600"/></span>{ar?'عرض الكل':'View all'}</button>{data.categories.map(c=><button type="button" key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)} className="text-center text-xs font-semibold"><span className={`mx-auto mb-2 block size-16 overflow-hidden rounded-full bg-neutral-100 ${selected===c.id?'ring-2 ring-red-500':''}`}>{c.image_url||c.products[0]?.image_url?<MenuImage src={c.image_url||c.products[0]?.image_url} alt="" className="h-full w-full" sizes="64px"/>:<span className="grid h-full place-items-center text-2xl text-red-600">{c.name.slice(0,1)}</span>}</span>{c.name}</button>)}</nav>
 {groups.map(c=><section key={c.id} className="mb-8"><h2 className="mb-4 text-xl font-bold">{c.name}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{c.products.map(productCard)}</div>{!c.products.length&&<p className="rounded-xl bg-neutral-50 p-5 text-sm text-neutral-500">{ar?'لا توجد منتجات حاليًا':'No products yet'}</p>}</section>)}
 </>}
 </main></div>;
}
