import {FullVatInvoiceButton} from '@/components/dashboard/FullVatInvoiceButton';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireManager} from '@/lib/membership';
import {createServerSupabase} from '@/lib/supabase/server';
import {getLocale} from '@/lib/i18n/server';
import {InvoiceView} from '@/components/dashboard/InvoiceView';
import {FinancialControls} from '@/components/dashboard/FinancialControls';
import type {PosReceipt} from '@/lib/thermal-print';
export const dynamic='force-dynamic';
export default async function Invoice({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{document?:string}>}){
 const [member,db,locale,{id},query]=await Promise.all([requireManager(),createServerSupabase(),getLocale(),params,searchParams]);
 const [{data:o},{data:events},{data:audit},{data:doc}]=await Promise.all([db.from('orders').select('*,order_items(*),restaurant_tables(label)').eq('id',id).eq('restaurant_id',member.restaurant.id).maybeSingle(),db.from('financial_events').select('*').eq('order_id',id).eq('restaurant_id',member.restaurant.id).order('id'),db.from('order_audit').select('*').eq('order_id',id).eq('restaurant_id',member.restaurant.id).order('id'),db.from('vat_documents').select('*').eq('order_id',id).eq('restaurant_id',member.restaurant.id).maybeSingle()]);if(!o)notFound();
 const refund=events?.find(e=>e.kind==='refund');const credit=query.document==='credit'&&Boolean(refund);
 const receipt:PosReceipt={orderId:o.id,fiscalState:o.fiscal_state,documentNumber:doc?.document_number,originalDocumentNumber:doc?.document_number,number:o.order_number,total:Number(o.total),currency:o.currency,received:Number(o.amount_received??o.total),payment:o.payment_method??'cash',tableLabel:o.restaurant_tables?.label??null,createdAt:doc?.created_at??o.created_at,paidAt:o.paid_at,note:credit?refund?.reason??'':o.note??'',fiscal:doc?.snapshot??o.fiscal_snapshot,creditNote:credit,creditDate:refund?.created_at,lines:o.order_items.map((i:{id:string;variant_id:string;product_name:string;variant_name:string;unit_price:number;quantity:number;line_total:number;net_total:number;vat_total:number;vat_rate:number;vat_code:string})=>({variantId:i.variant_id??i.id,name:i.product_name,variant:i.variant_name??'',price:Number(i.unit_price),quantity:i.quantity,gross:Number(i.line_total),net:Number(i.net_total),vat:Number(i.vat_total),rate:Number(i.vat_rate),code:i.vat_code}))};
 return <div className="mx-auto max-w-3xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">#{o.order_number} · {o.fiscal_state}</h1><Link href="/dashboard/orders" className="text-brand-700">{locale==='ar'?'الطلبات':'Orders'}</Link></header><section className="rounded-xl border bg-white p-4 text-sm">{o.order_source==='online'&&<p>{locale==='ar'?'طلب من رابط المنتجات':'Online order'} · {o.customer_details?.name} · <span dir="ltr">{o.customer_details?.phone}</span></p>}{o.customer_details?.address&&<p>{o.customer_details.address}</p>}{o.customer_details?.code&&<p>{locale==='ar'?'كود العميل':'Customer code'}: {o.customer_details.code}</p>}{o.fiscal_state==='unpaid'&&<p>{member.restaurant.business_kind==='supermarket'?(locale==='ar'?'غير مدفوع — الدفع عند الاستلام.':'Unpaid — pay on delivery.'):locale==='ar'?'غير مدفوع. راجع صورة التحويل مع العميل على واتساب ثم أكد الدفع بنفسك.':'Unpaid. Check transfer proof with the customer on WhatsApp, then confirm payment manually.'}</p>}</section><FinancialControls orderId={o.id} state={o.fiscal_state} legacyVoid={o.fiscal_state === "legacy" && !["completed","cancelled"].includes(o.status)} total={Number(o.total)}/>{!doc&&o.fiscal_state==='paid'&&o.fiscal_snapshot?.registered&&o.fiscal_snapshot?.mode!=='saudi'&&o.fiscal_snapshot?.invoice_kind!=='full'&&<FullVatInvoiceButton orderId={o.id}/>} {refund&&<div className="flex flex-wrap gap-4 text-sm"><Link className="text-brand-700" href={`/dashboard/orders/${id}`}>{locale==='ar'?'الفاتورة الأصلية':'Original invoice'}</Link><Link className="text-brand-700" href={`/dashboard/orders/${id}?document=credit`}>{locale==='ar'?'إشعار الاسترداد':'Refund credit note'}</Link></div>}<InvoiceView receipt={receipt} restaurantId={member.restaurant.id} fallbackName={member.restaurant.name}/><section><h2 className="mb-3 font-semibold">{locale==='ar'?'سجل العملية والتعديلات':'Transaction and audit journal'}</h2>{audit?.map(a=><details key={a.id} className="mb-2 rounded-xl border bg-white p-3 text-xs"><summary>#{a.id} · {a.entity} · {a.action} · {a.actor_name??'Guest / system'} · {new Date(a.created_at).toLocaleString('en-GB',{timeZone:member.restaurant.business_timezone})} · {a.reason}</summary><pre className="mt-3 overflow-x-auto" dir="ltr">{JSON.stringify({before:a.before_data,after:a.after_data},null,2)}</pre></details>)}</section></div>;
}
