export const infoPages = {
  privacy: { ar: 'سياسة الخصوصية', en: 'Privacy policy', sections: [
    ['البيانات اللي بنستخدمها', 'Information we use', 'بنستخدم بيانات الحساب والمطعم والمنيو والطلبات عشان نشغّل الخدمة. تسجيل الدخول بيستخدم ملفات ارتباط ضرورية، والإشعارات بتحتاج موافقتك.', 'We use account, restaurant, menu and order information to operate the service. Sign-in uses essential cookies. Browser notifications require your permission.'],
    ['استخدام البيانات وحمايتها', 'Use and protection', 'البيانات بتتعالج لتقديم الخدمة والدعم وحماية الحسابات. مزوّدو الاستضافة وقاعدة البيانات بيشاركوا في تشغيل الخدمة. صاحب المطعم مسؤول عن بيانات عملائه وصلاحيات فريقه، ومينفعش تضيف بيانات حساسة في ملاحظات الطلب.', 'Data is processed to provide the service, support and account security. Hosting and database providers help operate the service. Restaurant owners control their customer data and staff access. Do not include sensitive information in order notes.'],
    ['طلباتك بخصوص بياناتك', 'Your data requests', 'تقدر تتواصل مع الدعم لطلب تصحيح بياناتك أو نسخة منها أو حذف حسابك. بنراجع الطلب ونتأكد من ملكية الحساب، وقد يلزم الاحتفاظ ببعض السجلات لالتزامات قانونية أو حل نزاع.', 'Contact support to request correction, a copy of your data or account deletion. We verify account ownership and review the request. Some records may need to be retained for legal obligations or dispute resolution.']
  ]},
  terms: { ar: 'شروط الاستخدام', en: 'Terms of use', sections: [
    ['الخدمة', 'The service', 'MenuzQR بيساعد المطاعم والكافيهات تعرض المنيو وتدير الطلبات حسب الخدمات المفعّلة في حسابها. المنصة مش هي البائع للأكل أو المشروبات، والمطعم مسؤول عن التنفيذ والأسعار والمكونات والحساسية الغذائية.', 'MenuzQR helps restaurants publish menus and manage orders through the services enabled on their accounts. The restaurant, not MenuzQR, supplies food and drinks and is responsible for fulfillment, prices, ingredients and allergen information.'],
    ['الحساب والمحتوى', 'Accounts and content', 'صاحب الحساب مسؤول عن صحة البيانات وحقوق الصور والمحتوى اللي بيضيفه، وحماية بيانات الدخول واختيار صلاحيات الموظفين. ممنوع إساءة استخدام الخدمة أو محاولة الوصول لبيانات مطعم تاني.', 'Account owners are responsible for accurate information, rights to uploaded images and content, login security and staff permissions. Misuse of the service or attempts to access another restaurant’s data are prohibited.'],
    ['التفعيل والأسعار', 'Activation and pricing', 'راجع السعر والخدمات المعروضة في صفحة الاشتراك قبل الدفع. التفعيل حاليًا بيتم بالتنسيق مع الإدارة، والخدمات الإضافية زي الكاشير بتتحدد حسب الباقة المعروضة. أي تغيير في اتفاق الدفع لازم يتوضح قبل تأكيده.', 'Review the price and included services on the subscription page before paying. Activation is currently coordinated with administration. Optional services such as POS follow the displayed plan. Changes to a payment agreement must be clarified before confirmation.']
  ]},
  refunds: { ar: 'الإلغاء والاسترجاع', en: 'Cancellation and refunds', sections: [
    ['طلب الإلغاء أو الاسترجاع', 'Requesting cancellation or a refund', 'لو محتاج تلغي الخدمة أو تطلب استرجاع، تواصل مع الدعم ببيانات الحساب ومرجع الدفع وسبب الطلب. متبعتش كلمة السر أو بيانات البطاقة. الإدارة هتراجع حالة التفعيل والخدمة المتفق عليها وترد عليك بنتيجة الطلب.', 'To request cancellation or a refund, contact support with your account details, payment reference and reason. Do not send passwords or card details. Administration will review activation status and the agreed service and respond with the outcome.'],
    ['قبل تأكيد الدفع', 'Before payment', 'اطلب توضيح شروط الإلغاء والاسترجاع الخاصة بالعرض قبل تأكيد الدفع. الصفحة دي مش ضمان لقبول كل طلب، ومش بتلغي أي حقوق إلزامية للمستهلك وفق القانون المطبق.', 'Ask for the cancellation and refund conditions of your offer before confirming payment. This page does not guarantee approval of every request or override mandatory consumer rights under applicable law.'],
    ['طلبات المطاعم', 'Restaurant orders', 'إلغاء أو استرجاع قيمة الأكل والمشروبات بيتم مع المطعم نفسه، لأنه المسؤول عن الطلب وتنفيذه.', 'Food and drink cancellations and refunds are handled by the restaurant responsible for the order.']
  ]},
  about: { ar: 'عن MenuzQR', en: 'About MenuzQR', sections: [
    ['منيو مطعمك في مكان واحد', 'Your restaurant menu in one place', 'MenuzQR خدمة رقمية للمطاعم والكافيهات: جهّز منيو، ضيف أقسام ومنتجات وصور وأسعار، وشاركه بكود QR. تقدر تتابع طلبات الترابيزات وتوزّع شغل الفريق حسب الخدمات المتاحة في حسابك.', 'MenuzQR is a digital service for restaurants and cafés. Create a menu with categories, products, photos and prices, then share it with a QR code. Track table orders and organize your team through the services available on your account.'],
    ['تسليم الخدمة', 'Service delivery', 'الخدمة بتتقدم أونلاين من خلال حسابك ورابط المنيو. مفيش شحن منتجات مادية ضمن خدمة المنيو الرقمي.', 'The service is delivered online through your account and menu link. Digital menu services do not include shipping physical goods.']
  ]},
  contact: { ar: 'تواصل معانا', en: 'Contact us', sections: [
    ['نقدر نساعدك إزاي؟', 'How can we help?', 'لو عندك سؤال عن التفعيل أو استخدام المنيو أو مشكلة في حسابك، تواصل معانا من بيانات الدعم تحت. ابعت وصف المشكلة واسم مطعمك من غير كلمة السر.', 'For activation, menu setup or account support, use the contact details below. Include a description and your restaurant name, without your password.']
  ]}
} as const;
export type InfoPage = keyof typeof infoPages;
