import type {FiscalSnapshot} from './tax';
export type ExportInvoice={id:string;order_number:number;created_at:string;status:string;fiscal_state:string;currency:string;total:number;payment_method:string|null;paid_at:string|null;note:string|null;fiscal_snapshot:FiscalSnapshot|null;customer_details?:{name?:string;phone?:string;address?:string;code?:string};order_items:{product_name:string;variant_name:string|null;quantity:number;unit_price:number;line_total:number;vat_rate?:number;vat_total?:number}[];financial_events:unknown[];vat_documents:unknown[]};
export function escapeHtml(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function invoiceHtml(o:ExportInvoice,name:string){const e=escapeHtml,f=o.fiscal_snapshot;return `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>فاتورة ${e(o.order_number)}</title><style>body{font:16px Arial;max-width:800px;margin:40px auto;padding:20px}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #ddd;text-align:right}small{color:#666}@media print{button{display:none}}</style><h1>${e(f?.legal_name??name)}</h1><p>${e(f?.address)}</p>${f?.registered?`<p>VAT: ${e(f.vat_number)}</p>`:''}<h2>إيصال / Receipt #${e(o.order_number)}</h2><p>${e(o.created_at)} · ${e(o.currency)}</p><p>حالة الطلب: ${e(o.status)} · حالة الدفع: ${e(o.fiscal_state)} ${o.payment_method?`· ${e(o.payment_method)}`:''}</p><p>${e(o.customer_details?.name??f?.customer?.name)} ${e(o.customer_details?.phone)}</p><p>${e(o.customer_details?.address)} ${e(o.customer_details?.code)}</p><table><thead><tr><th>الصنف</th><th>الكمية</th><th>الإجمالي</th><th>VAT</th></tr></thead><tbody>${o.order_items.map(i=>`<tr><td>${e(i.product_name)} ${e(i.variant_name)}</td><td>${e(i.quantity)}</td><td>${e(i.line_total)}</td><td>${e(i.vat_total)} (${e(i.vat_rate)}%)</td></tr>`).join('')}</tbody></table><p>قبل الضريبة: ${e(f?.net??'غير مسجل')} · VAT: ${e(f?.vat??'غير مسجل')}</p><h3>الإجمالي: ${e(o.total)} ${e(o.currency)}</h3><p>${e(o.note)}</p><small>الحالة المالية وسجل العمليات والفواتير الضريبية الصادرة محفوظة في ملف JSON المرفق. إيصال البيع لا يحل محل فاتورة ضريبية كاملة.</small><p><button onclick="window.print()">طباعة / حفظ PDF</button></p></html>`;}
// Uncompressed UTF-8 ZIP for browsers without directory access.
export function zipFiles(files:{name:string;content:string}[]):Uint8Array {
 const enc=new TextEncoder();let offset=0;const parts:Uint8Array[]=[],central:Uint8Array[]=[];
 const header=(size:number)=>new Uint8Array(size);
 const crc=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
 if(files.length>65535)throw new Error('Too many files for one archive');
 for(const f of files){if(f.name.startsWith('/')||f.name.split('/').includes('..'))throw new Error('Invalid archive path');const name=enc.encode(f.name),data=enc.encode(f.content),sum=crc(data);const local=header(30),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,sum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);const c=header(46),w=new DataView(c.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,sum,true);w.setUint32(20,data.length,true);w.setUint32(24,data.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);parts.push(local,name,data);central.push(c,name);offset+=local.length+name.length+data.length;}
 const size=central.reduce((n,b)=>n+b.length,0);if(offset+size>0xffffffff)throw new Error('Archive too large');const end=header(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);const out=new Uint8Array(offset+size+22);let at=0;for(const part of [...parts,...central,end]){out.set(part,at);at+=part.length;}return out;
}
