import {businessDayRange} from '@/lib/business-time';
import Link from 'next/link';
import {requireManager} from '@/lib/membership';
import {createAdminSupabase} from '@/lib/supabase/admin';
import {getLocale} from '@/lib/i18n/server';
import {SalesSummary} from '@/components/dashboard/SalesSummary';
import {CloseDayButton} from '@/components/dashboard/CloseDayButton';
import type {SalesSummary as Summary} from '@/lib/tax';
export const dynamic='force-dynamic';
export const metadata={title:'Sales and VAT reports'};
export default async function Reports({searchParams}:{searchParams:Promise<{date?:string}>}){
 const [member,locale,params]=await Promise.all([requireManager('/dashboard/reports'),getLocale(),searchParams]);const ar=locale==='ar';const l=(a:string,e:string)=>ar?a:e;const r=member.restaurant;
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:r.business_timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());let date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??'')?params.date!:today;try{businessDayRange(date,r.business_timezone);}catch{date=today;}
 const db=createAdminSupabase();const [report,zs,events,audit]=await Promise.all([db.rpc('daily_fiscal_report',{p_actor:member.userId,p_restaurant:r.id,p_day:date}),db.from('z_reports').select('*').eq('restaurant_id',r.id).order('report_number',{ascending:false}).limit(30),db.from('financial_events').select('id,order_id,kind,document_number,currency,gross,actor_name,reason,created_at').eq('restaurant_id',r.id).order('id',{ascending:false}).limit(50),db.from('order_audit').select('id,order_id,entity,action,actor_name,reason,created_at').eq('restaurant_id',r.id).order('id',{ascending:false}).limit(50)]);
 if(report.error||zs.error||events.error||audit.error)throw new Error('Could not load financial reports');
 return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">{l('المبيعات والضريبة وإغلاق اليوم','Sales, VAT and end of day')}</h1><p className="mt-2 text-sm text-ink-500">{r.business_timezone} · {l('البيع عند تسجيل الدفع. الاسترداد يظهر في يوم تنفيذه.','Sales are recorded at payment. Refunds appear on the day they occur.')}</p></header>
 <form className="flex flex-wrap items-end gap-3"><label className="text-sm">{l('تقرير يوم','Daily report')}<input type="date" name="date" defaultValue={date} required className="ms-3 rounded-xl border bg-white p-2"/></label><button className="rounded-xl border bg-white px-4 py-2">{l('عرض','View')}</button><a className="rounded-xl border bg-white px-4 py-2 text-sm" href={`/dashboard/reports/export?date=${date}&kind=events`}>CSV {l('المبيعات','Sales')}</a><a className="rounded-xl border bg-white px-4 py-2 text-sm" href={`/dashboard/reports/export?date=${date}&kind=audit`}>CSV {l('سجل التعديلات','Audit journal')}</a></form>
 <SalesSummary summary={report.data as Summary} ar={ar}/>
 <p className="text-xs text-ink-500">{l('التسجيل الضريبي يبدأ من تفعيل التحديث. الطلبات القديمة محفوظة بدون افتراض معدلات ضريبة تاريخية. تصدير CSV متاح للمحاسب؛ تقديم إقرارات MTD إلى HMRC غير مربوط حاليًا.','Fiscal recording starts with this update. Historical orders are retained without inventing past VAT rates. CSV export is available for your accountant; HMRC MTD return submission is not connected.')}</p>
 <CloseDayButton/>
 <section className="rounded-2xl border bg-white p-4"><h2 className="mb-3 font-semibold">{l('تقارير Z المحفوظة','Saved Z reports')}</h2><ul className="space-y-2">{zs.data?.map(z=><li key={z.id}><Link className="text-brand-700" href={`/dashboard/reports/${z.id}`}>Z #{z.report_number} · {z.business_date} · {z.closed_by_name}</Link></li>)}{!zs.data?.length&&<li className="text-sm text-ink-500">{l('لسه مفيش إغلاق محفوظ.','No saved close yet.')}</li>}</ul></section>
 <section className="rounded-2xl border bg-white p-4"><h2 className="mb-3 font-semibold">{l('آخر ٥٠ عملية مالية','Latest 50 financial events')}</h2><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{events.data?.map(e=><tr key={e.id} className="border-t"><td className="p-2"><Link href={`/dashboard/orders/${e.order_id}`} className="text-brand-700">{e.document_number}</Link></td><td className="p-2">{e.kind}</td><td className="p-2">{e.gross} {e.currency}</td><td className="p-2">{e.actor_name}</td><td className="p-2">{new Date(e.created_at).toLocaleString(ar?'ar-EG':'en-GB',{timeZone:r.business_timezone})}</td><td className="p-2">{e.reason}</td></tr>)}</tbody></table></div></section>
 <section className="rounded-2xl border bg-white p-4"><h2 className="mb-3 font-semibold">{l('آخر ٥٠ تعديل في السجل','Latest 50 journal entries')}</h2><ul className="space-y-2 text-xs">{audit.data?.map(a=><li key={a.id} className="border-t py-2">#{a.id} · {a.entity} · {a.action} · {a.actor_name??l('عميل أو سيستم','Guest or system')} · {new Date(a.created_at).toLocaleString(ar?'ar-EG':'en-GB',{timeZone:r.business_timezone})} {a.reason&&`· ${a.reason}`} {a.order_id&&<Link href={`/dashboard/orders/${a.order_id}`} className="text-brand-700">{l('تفاصيل','Details')}</Link>}</li>)}</ul></section></div>;
}
