"use client";
import {useActionState} from 'react';
import {saveDomain,checkDomain,toggleDomain} from '@/lib/actions/domains';
import {SubmitButton} from '@/components/ui/SubmitButton';
import type {TenantDomain} from '@/lib/tenant-domain';
function Check({domain}:{domain:TenantDomain}){
 const [state,action]=useActionState(checkDomain,null);
 return <form action={action} className="mt-3 space-y-3"><input type="hidden" name="domain_id" value={domain.id}/><details><summary className="cursor-pointer text-xs">إعداد اتصال Vercel</summary><p className="mt-2 text-xs text-ink-500">لو اتصال السيرفر مش متظبط، أدخل Vercel token بصلاحية إدارة المشروع. بيتستخدم للطلب ده فقط ومش بيتحفظ.</p><input type="password" name="vercel_token" autoComplete="off" placeholder="Vercel token" className="mt-2 w-full rounded-xl border p-2"/></details>{state?.message&&<p role="status" className="text-sm">{state.message}</p>}<SubmitButton>ربط وفحص DNS</SubmitButton></form>;
}
export function BusinessDomainForm({restaurantId,domains}:{restaurantId:string;domains:TenantDomain[]}){
 const [state,action]=useActionState(saveDomain,null);
 return <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-semibold">الدومين الخاص والصفحة الرئيسية</h2><p className="text-sm text-ink-500">نفس الحساب ونفس البيانات، على دومين العميل. تقدر تضيف الدومين الأساسي وwww كل واحد منفصل، وتفعّلهم بعد التحقق.</p><form action={action} className="space-y-3"><input type="hidden" name="restaurant_id" value={restaurantId}/><label className="block text-sm">الدومين<input name="hostname" required dir="ltr" placeholder="shop.example.com" className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm">الصفحة الرئيسية<select name="home_mode" className="mt-1 w-full rounded-xl border p-3"><option value="landing">صفحة تعريف بالنشاط</option><option value="login">صفحة دخول الموظفين</option></select></label>{state?.message&&<p role="status" className="text-sm">{state.message}</p>}<SubmitButton>حفظ الدومين</SubmitButton></form>{domains.map(d=><div key={d.id} className="rounded-xl border p-4"><p dir="ltr" className="break-all font-semibold">{d.hostname}</p><p className="mt-1 text-sm">{d.enabled?(d.status==='active'?'مفعّل':'في انتظار التحقق'):'متوقف'} · {d.home_mode==='login'?'صفحة دخول':'صفحة تعريف'}</p><p className="mt-2 text-xs text-ink-500">لتغيير الصفحة الرئيسية، احفظ نفس الدومين بالاختيار الجديد. الموقع العام للأصناف متاح على /menu.</p>{d.checked_at&&<div className="mt-3 overflow-x-auto"><p className="mb-2 text-xs text-ink-500">أضف السجلات المناسبة عند شركة الدومين. اختار A للدومين الأساسي أو CNAME للدومين الفرعي؛ لا تضفهم معًا لنفس الاسم. سجلات TXT للتحقق لو مطلوبة.</p><table className="w-full text-start text-xs"><thead><tr><th className="p-2">النوع</th><th className="p-2">الاسم</th><th className="p-2">القيمة</th></tr></thead><tbody>{d.verification.verification?.map((v,i)=><tr key={'txt'+i}><td className="p-2">{v.type}</td><td dir="ltr" className="p-2">{v.domain}</td><td dir="ltr" className="select-all break-all p-2">{v.value}</td></tr>)}{d.verification.recommendedCNAME?.filter(v=>v.rank===1).map(v=><tr key={v.value}><td className="p-2">CNAME</td><td dir="ltr" className="p-2">{d.hostname}</td><td dir="ltr" className="select-all p-2">{v.value}</td></tr>)}{d.verification.recommendedIPv4?.filter(v=>v.rank===1).flatMap(v=>v.value.map(ip=><tr key={ip}><td className="p-2">A</td><td dir="ltr" className="p-2">{d.hostname}</td><td dir="ltr" className="select-all p-2">{ip}</td></tr>))}</tbody></table></div>}<Check domain={d}/><form action={toggleDomain} className="mt-3"><input type="hidden" name="domain_id" value={d.id}/><input type="hidden" name="enabled" value={String(!d.enabled)}/><button className="text-sm underline">{d.enabled?'إيقاف الدومين':'تشغيل الدومين'}</button></form></div>)}</section>;
}
